version: '1.0'
kind: pipeline
metadata:
  name: Benchprep/demo1
  project: Benchprep
  projectId: 61df0fc334f0d1c92cb6c815
  revision: 5
  accountId: 600edc0bdffeb2bc4981d15a
  created_at: '2022-01-12T17:29:45.201Z'
  updated_at: '2022-01-12T17:34:47.797Z'
  shortName: demo1
  deprecate: {}
  originalYamlString: |+
    # More examples of Codefresh YAML can be found at
    # https://codefresh.io/docs/docs/yaml-examples/examples/

    version: "1.0"
    # Stages can help you organize your steps in stages
    stages:
      - "clone"
      - "build"
      - "test"

    steps:
      clone:
        title: "Cloning repository"
        type: "git-clone"
        repo: "lrochette/CF-tests"
        # CF_BRANCH value is auto set when pipeline is triggered
        # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
        revision: "${{CF_BRANCH}}"
        git: "github"
        stage: "clone"

      build:
        title: "Building Docker image"
        type: "build"
        image_name: "lrochette/demo1"
        working_directory: "${{clone}}"
        tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
        dockerfile: "gresearch/Dockerfile"
        registry: docker-lr
        stage: "build"

      test:
        title: "Running test"
        type: "freestyle" # Run any command
        image: "ubuntu:latest" # The image in which command will be executed
        working_directory: "${{clone}}" # Running command where code cloned
        commands:
          - "ls"
        stage: "test"

  id: 61df1009ad9a56119a24a3ef
spec:
  triggers:
    - name: lrochette/CF-tests
      type: git
      repo: lrochette/CF-tests
      events:
        - push.heads
      pullRequestAllowForkEvents: false
      commentRegex: /.*/gi
      branchRegex: /.*/gi
      branchRegexInput: regex
      provider: github
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
      context: github
      contexts: []
      verified: true
      status: verified
      lastExecutionDate: '2022-01-12T17:50:26.393Z'
      id: 61df100bad9a56bd6724a3f0
      endpoint: 'https://g.codefresh.io/api/providers/github/hook/AbV2oP2l0Q'
      secret: 9Ugdk3MgW4icmtMc
  stages:
    - clone
    - build
    - test
  variables: []
  contexts: []
  debug:
    steps:
      clone:
        phases:
          before: true
          override: false
          after: false
      test:
        phases:
          before: false
          override: true
          after: false
  steps:
    clone:
      title: Cloning repository
      type: git-clone
      repo: lrochette/CF-tests
      revision: '${{CF_BRANCH}}'
      git: github
      stage: clone
    build:
      title: Building Docker image
      type: build
      image_name: lrochette/demo1
      working_directory: '${{clone}}'
      tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
      dockerfile: gresearch/Dockerfile
      registry: docker-lr
      stage: build
    test:
      title: Running test
      type: freestyle
      image: 'ubuntu:latest'
      working_directory: '${{clone}}'
      commands:
        - ls
      stage: test

