apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ${shortName}
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  ${provider}:
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo/${provider}-${uuid}
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
