apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ${project_name}-${short_name}-pipeline-template
spec:
  volumes: []
  arguments:
    parameters: []
  entrypoint: pipeline
  templates:
    - name: pipeline
      inputs:
        parameters: []
      dag:
        tasks: []
          #
          # insert steps here
          #
    #
    # insert additional templates here for freestyle
    #   volume mounts?
    #
