apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: xxx-when6-pipeline-template
spec:
  arguments:
    parameters: []
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: image
            value: ubuntu:latest
          - name: working_directory
            value: /codefresh/volume
          - name: shell
            value: bash
          - name: commands
            value: |+
              if [ (1 + $RANDOM % 10) < 6 ] ; then exit 0; else exit 1; fi

        # continueOn:
        #   failed: true
        name: init
        templateRef:
          name: c2csdp.freestyle.0.0.1
          template: freestyle
      - arguments:
          parameters:
          - name: image
            value: ubuntu:latest
          - name: working_directory
            value: /codefresh/volume
          - name: shell
            value: sh
          - name: commands
            value: |+
              echo success

        # continueOn:
        #   failed: false
        depends: init && (init.Succeeded)
        name: good
        templateRef:
          name: c2csdp.freestyle.0.0.1
          template: freestyle
      - arguments:
          parameters:
          - name: image
            value: ubuntu:latest
          - name: working_directory
            value: /codefresh/volume
          - name: shell
            value: sh
          - name: commands
            value: |+
              echo falure

        # continueOn:
        #   failed: true
        depends: good && (init.Errored)
        name: bad
        templateRef:
          name: c2csdp.freestyle.0.0.1
          template: freestyle
      - arguments:
          parameters:
          - name: image
            value: ubuntu:latest
          - name: working_directory
            value: /codefresh/volume
          - name: shell
            value: sh
          - name: commands
            value: |+
              echo falure

        # continueOn:
        #   failed: true
        depends: bad && (init.Succeeded|| init.Errored)
        name: always
        templateRef:
          name: c2csdp.freestyle.0.0.1
          template: freestyle
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
    name: pipeline
  volumes: []
