apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxx-delivery-pipelines
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: yeti2-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/yeti2/github-2eb385fc-8eec-11ec-838a-acde48001122
        pathType: ImplementationSpecific
