apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxx-delivery-pipelines
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: yeti2-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/yeti2/github-2eb385fc-8eec-11ec-838a-acde48001122
        pathType: ImplementationSpecific
      - backend:
          service:
            name: yeti2-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/yeti2/github-2abcb306-8ef1-11ec-b779-acde48001122
        pathType: ImplementationSpecific
      - backend:
          service:
            name: yeti2-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/yeti2/github-6d7afee6-8ef1-11ec-a391-acde48001122
        pathType: ImplementationSpecific
      - backend:
          service:
            name: yeti2-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/yeti2/github-872cbff0-8ef1-11ec-a49d-acde48001122
        pathType: ImplementationSpecific
      - backend:
          service:
            name: yeti2-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/yeti2/github-06d8da18-8ef2-11ec-b1ec-acde48001122
        pathType: ImplementationSpecific
