apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxx-delivery-pipelines
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: when6-eventsource-svc
            port:
              number: 80
        path: /webhooks/xxx/when6/github-de8c2a4a-98f3-11ec-a53e-acde48001122
        pathType: ImplementationSpecific
