apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: yeti2-pipeline-template
spec:
  arguments:
    parameters: null
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: CF_REPO_OWNER
            value: '{{ inputs.parameters.CF_REPO_OWNER }}'
          - name: CF_REPO_NAME
            value: '{{ inputs.parameters.CF_REPO_NAME }}'
          - name: CF_BRANCH
            value: main
        name: clone
        templateRef:
          name: c2csdp.git-clone.0.0.1
          template: git-clone
      - depends: clone
        name: test
        template: test
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
    name: pipeline
  - name: test
    script:
      command:
      - - sh
      image: ubuntu:latest
      source: 'ls

        '
      volumeMounts:
      - mountPath: /codefresh/volume
        name: codefresh-volume
      workingDir: '{{tasks.clone.outputs.parameters.WORKING_DIR}}'
