apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: yeti2-pipeline-template
spec:
  arguments:
    parameters: null
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - depends: clone
        name: test
        template: test
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
    name: pipeline
  - arguments:
      parameters:
      - name: CF_REPO_OWER
        value: ${CF_REPO_OWNER}
      - name: CF_REPO_NAME
        value: ${CF_REPO_NAME}
      - name: CF_BRANCH
        value: main
    name: clone
    templateRef:
      name: c2csdp.git-clone.0.0.1
      template: git-clone
  - name: test
    script:
      command:
      - - sh
      image: ubuntu:latest
      source: 'ls

        '
      volumeMounts:
      - mountPath: /codefresh/volume
        name: codefresh-volume
      workingDir: '{{tasks.clone.outputs.parameters.WORKING_DIR}}'
