apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: yeti1
spec:
  eventBusName: codefresh-eventbus
  github:
    github-cd192e9a-8df2-11ec-9968-acde48001122:
      active: true
      apiToken:
        key: git_token
        name: autopilot-secret
      contentType: json
      deleteHookOnFinish: true
      events:
      - push.heads
      insecure: false
      repositories:
      - names:
        - yeti-test
        owner: lrochette
      webhook:
        endpoint: /webhooks/xxx/yeti1/github-cd192e9a-8df2-11ec-9968-acde48001122
        method: POST
        port: '80'
        url: https://lrcsdp.support.cf-cd.com
  service:
    ports:
    - port: 80
  template:
    serviceAccountName: argo-server
