apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: yeti1-pipeline-template
spec:
  arguments:
    parameters: null
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - name: test
        template: test
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
    name: pipeline
  - name: test
    script:
      command: [sh]
      image: ubuntu:latest
      source:
      - ls
      volumeMounts:
      - mountPath: /codefresh/volume
        name: codefresh-volume
      workingDir: /codefresh/volume
