apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: xxx-yeti2-pipeline-template
spec:
  arguments:
    parameters: []
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: CF_REPO_OWNER
            value: '{{ inputs.parameters.CF_REPO_OWNER }}'
          - name: CF_REPO_NAME
            value: '{{ inputs.parameters.CF_REPO_NAME }}'
          - name: CF_BRANCH
            value: main
        continueOn:
          failed: false
        name: clone
        templateRef:
          name: c2csdp.git-clone.0.0.1
          template: git-clone
      - arguments:
          parameters:
          - name: image
            value: ubuntu:latest
          - name: working_directory
            value: '{{ tasks.clone.outputs.parameters.WORKING_DIR }}'
          - name: shell
            value: sh
          - name: commands
            value: |+
              ls

        continueOn:
          failed: false
        depends: clone
        name: test
        templateRef:
          name: c2csdp.freestyle.0.0.1
          template: freestyle
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
    name: pipeline
  volumes: []
