apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: yeti5-pipeline-template
spec:
  arguments:
    parameters: []
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: CF_REPO_OWNER
            value: lrochette
          - name: CF_REPO_NAME
            value: yeti-test
          - name: CF_BRANCH
            value: '{{ inputs.parameters.CF_BRANCH }}'
        name: clone
        templateRef:
          name: c2csdp.git-clone.0.0.1
          template: git-clone
      - arguments:
          parameters:
          - name: image_name
            value: lrochette/yeti4
          - name: tag
            value: latest
          - name: dockerfile
            value: Dockerfile
          - name: working_directory
            value: '{{ tasks.clone.outputs.parameters.WORKING_DIR }}'
          - name: docker-config
            value: docker-lr
        depends: clone
        name: build
        templateRef:
          name: c2csdp.build.0.0.1
          template: build
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
      - name: VAR1
      - name: VAR2
    name: pipeline
  volumes:
  - name: docker-lr
    secret:
      items:
      - key: .dockerconfigjson
        path: config.json
      secretName: docker-lr
