apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: yeti1-pipeline-template
spec:
  arguments:
    parameters: []
  entrypoint: pipeline
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: image
            value: ubuntu:latest
          - name: working_directory
            value: /codefresh/volume
          - name: shell
            value: sh
          - name: commands
            value: |+
              echo bar
              ls
              echo foo

        name: test
        templateRef:
          name: c2csdp.freestyle.0.0.1
          template: freestyle
    inputs:
      parameters:
      - name: CF_REPO_OWNER
      - name: CF_REPO_NAME
      - name: CF_BRANCH
      - name: VAR1
        value: value1
    name: pipeline
  volumes: []
